[package]
name = "onepass"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
hmac-sha256 = "1.1.7"
termcolor = "1.4.1"
clipboard = "0.5.0"
rpassword = "7.3.1"
ctrlc = "3.4.5"
